### ISSUE TITLE
Error while trying to run Demo app

### ISSUE THREAD

**Issue by SantosLV** [aws/amazon-chime-sdk-cpp#12]
Hi guys, 

I am following the instructions to build the demo app. I am running an Ubuntu 18.04 (x86_64) EC2 Instance.

In step 2, when I run 

`fetch --nohooks webrtc &&\`

I get the following warnings:

```
7>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/src/tools" "/home/tchubinsky/webrtc-build/src/_gclient_tools_cwu5qmkj"' in /home/ubuntu/webrtc-build failed; will retry after a short nap...
6>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/src/third_party" "/home/tchubinsky/webrtc-build/src/_gclient_third_party_fbcdtteg"' in /home/ubuntu/webrtc-build failed; will retry after a short nap...
```

After a while, I get this:

```
[0:19:08] Still working on:
[0:19:08]   src/third_party
Syncing projects:  26% (12/46) src/third_party
src/tools (ERROR)
----------------------------------------
[0:01:00] Started.
[0:01:00] 

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src/tools /home/ubuntu/webrtc-build/src/_gclient_tools_cho9slqy' in '/home/ubuntu/webrtc-build'

[0:01:01] Cloning into '/home/ubuntu/webrtc-build/src/_gclient_tools_cho9slqy'...
[0:01:01] remote: Sending approximately 1.16 GiB ...
[0:01:01] remote: Counting objects: 1   
[0:01:01] remote: Counting objects: 971, done
[0:01:01] remote: Finding sources:   1% (10/971)   
[0:01:01] remote: Finding sources:  10% (98/971)   
[0:01:01] remote: Finding sources: 100% (971/971)   
[0:01:01] Receiving objects:   0% (1/493734)   
[0:01:03] Receiving objects:   0% (966/493734), 3.54 MiB | 1.75 MiB/s   
[0:01:04] Receiving objects:   1% (4938/493734), 5.79 MiB | 1.91 MiB/s   
[0:01:06] Receiving objects:   2% (9875/493734), 8.05 MiB | 1.99 MiB/s   
[0:01:07] Receiving objects:   3% (14813/493734), 11.44 MiB | 2.12 MiB/s   
[0:01:08] Receiving objects:   3% (19694/493734), 13.52 MiB | 2.20 MiB/s   
[0:01:10] Receiving objects:   5% (24687/493734), 17.22 MiB | 2.27 MiB/s   
[0:01:11] Receiving objects:   6% (29625/493734), 19.71 MiB | 2.31 MiB/s   
[0:01:12] Receiving objects:   7% (34562/493734), 22.04 MiB | 2.32 MiB/s   
[0:01:13] Receiving objects:   8% (39499/493734), 24.49 MiB | 2.41 MiB/s   
[0:01:14] Receiving objects:   9% (44437/493734), 27.11 MiB | 2.45 MiB/s   
[0:01:15] Receiving objects:  10% (49374/493734), 29.76 MiB | 2.48 MiB/s   
[0:01:16] Receiving objects:  11% (56616/493734), 33.41 MiB | 2.52 MiB/s   
[0:01:17] Receiving objects:  12% (62202/493734), 35.88 MiB | 2.52 MiB/s   
[0:01:19] Receiving objects:  14% (69123/493734), 39.50 MiB | 2.42 MiB/s   
[0:01:20] Receiving objects:  16% (78998/493734), 43.04 MiB | 2.36 MiB/s   
[0:01:21] Receiving objects:  26% (128371/493734), 46.87 MiB | 2.67 MiB/s   
[0:01:22] Receiving objects:  36% (177745/493734), 50.99 MiB | 3.02 MiB/s   
[0:01:23] Receiving objects:  49% (241930/493734), 55.58 MiB | 3.54 MiB/s   
[0:01:24] Receiving objects:  61% (301178/493734), 60.83 MiB | 4.19 MiB/s   
[0:01:25] Receiving objects:  71% (353160/493734), 66.00 MiB | 4.69 MiB/s   
[0:01:27] Receiving objects:  72% (359699/493734), 71.62 MiB | 4.07 MiB/s   
[0:01:29] Receiving objects:  73% (363463/493734), 76.42 MiB | 2.79 MiB/s   
[0:01:30] Receiving objects:  73% (363579/493734), 78.61 MiB | 2.39 MiB/s   
[0:01:33] Receiving objects:  74% (366623/493734), 83.55 MiB | 2.38 MiB/s   
[0:01:34] Receiving objects:  74% (369076/493734), 88.91 MiB | 2.43 MiB/s   
[0:01:36] Receiving objects:  74% (369610/493734), 94.92 MiB | 2.79 MiB/s   
[0:01:38] Receiving objects:  74% (370018/493734), 97.96 MiB | 2.90 MiB/s   
[0:01:39] Receiving objects:  75% (370410/493734), 104.03 MiB | 3.02 MiB/s   
[0:01:41] Receiving objects:  75% (370770/493734), 106.84 MiB | 2.98 MiB/s   
[0:01:43] Receiving objects:  75% (371086/493734), 112.74 MiB | 2.94 MiB/s   
[0:01:44] Receiving objects:  75% (371294/493734), 115.68 MiB | 2.91 MiB/s   
[0:01:45] Receiving objects:  75% (371929/493734), 121.78 MiB | 3.00 MiB/s   
[0:01:46] Receiving objects:  75% (372170/493734), 124.80 MiB | 3.01 MiB/s   
[0:01:48] Receiving objects:  75% (373179/493734), 130.51 MiB | 2.93 MiB/s   
[0:01:50] Receiving objects:  75% (374122/493734), 133.57 MiB | 2.95 MiB/s   
[0:01:51] Receiving objects:  76% (375238/493734), 138.03 MiB | 2.93 MiB/s   
[0:01:53] Receiving objects:  76% (376385/493734), 142.40 MiB | 2.94 MiB/s   
[0:01:54] Receiving objects:  76% (377366/493734), 145.30 MiB | 2.95 MiB/s   
[0:01:56] Receiving objects:  76% (378762/493734), 151.16 MiB | 2.91 MiB/s   
[0:01:57] Receiving objects:  77% (380176/493734), 155.51 MiB | 2.91 MiB/s   
[0:01:59] Receiving objects:  77% (381490/493734), 159.89 MiB | 2.89 MiB/s   
[0:02:00] Receiving objects:  77% (382551/493734), 165.51 MiB | 2.84 MiB/s   
[0:02:02] Receiving objects:  77% (383171/493734), 168.23 MiB | 2.82 MiB/s   
[0:02:03] Receiving objects:  77% (384385/493734), 173.69 MiB | 2.74 MiB/s   
[0:02:05] Receiving objects:  77% (384986/493734), 179.70 MiB | 2.84 MiB/s   
[0:02:06] Receiving objects:  78% (385339/493734), 182.43 MiB | 2.83 MiB/s   
[0:02:08] Receiving objects:  78% (386552/493734), 187.69 MiB | 2.80 MiB/s   
[0:02:10] Receiving objects:  78% (387104/493734), 190.84 MiB | 2.87 MiB/s   
[0:02:11] Receiving objects:  78% (387962/493734), 197.44 MiB | 3.03 MiB/s   
[0:02:12] Receiving objects:  78% (388434/493734), 201.19 MiB | 3.29 MiB/s   
[0:02:14] Receiving objects:  79% (390050/493734), 205.23 MiB | 3.57 MiB/s   
[0:02:15] Receiving objects:  79% (391282/493734), 211.10 MiB | 3.73 MiB/s   
[0:02:17] Receiving objects:  79% (392461/493734), 221.50 MiB | 4.04 MiB/s   
[0:02:18] Receiving objects:  79% (393235/493734), 225.44 MiB | 4.01 MiB/s   
[0:02:19] Receiving objects:  79% (394007/493734), 229.42 MiB | 4.07 MiB/s   
[0:02:21] Receiving objects:  80% (396164/493734), 235.48 MiB | 4.02 MiB/s   
[0:02:22] Receiving objects:  80% (396593/493734), 241.66 MiB | 4.04 MiB/s   
[0:02:24] Receiving objects:  80% (398882/493734), 249.95 MiB | 4.10 MiB/s   
[0:02:25] Receiving objects:  80% (399599/493734), 254.10 MiB | 4.13 MiB/s   
[0:02:26] Receiving objects:  81% (400544/493734), 258.30 MiB | 4.13 MiB/s   
[0:02:27] Receiving objects:  81% (401602/493734), 262.39 MiB | 4.14 MiB/s   
[0:02:28] Receiving objects:  81% (402633/493734), 266.47 MiB | 4.11 MiB/s   
[0:02:29] Receiving objects:  81% (403423/493734), 270.32 MiB | 4.05 MiB/s   
[0:02:31] Receiving objects:  81% (404207/493734), 280.30 MiB | 4.40 MiB/s   
[0:02:32] Receiving objects:  82% (405116/493734), 285.15 MiB | 4.58 MiB/s   
[0:02:34] Receiving objects:  82% (406317/493734), 293.08 MiB | 4.52 MiB/s   
[0:02:35] Receiving objects:  82% (407051/493734), 297.03 MiB | 4.30 MiB/s   
[0:02:36] Receiving objects:  82% (407599/493734), 301.12 MiB | 4.07 MiB/s   
[0:02:38] Receiving objects:  82% (408811/493734), 306.80 MiB | 3.89 MiB/s   
[0:02:39] Receiving objects:  82% (408917/493734), 312.38 MiB | 3.83 MiB/s   
[0:02:40] Receiving objects:  82% (408999/493734), 317.18 MiB | 3.99 MiB/s   
[0:02:41] Receiving objects:  82% (409108/493734), 322.25 MiB | 4.27 MiB/s   
[0:02:42] Receiving objects:  82% (409541/493734), 327.23 MiB | 4.53 MiB/s   
[0:02:44] Receiving objects:  82% (409725/493734), 334.91 MiB | 5.00 MiB/s   
[0:02:45] Receiving objects:  82% (409794/493734), 342.39 MiB | 5.05 MiB/s   
[0:02:46] Receiving objects:  83% (409860/493734), 347.39 MiB | 5.03 MiB/s   
[0:02:47] Receiving objects:  83% (410022/493734), 352.33 MiB | 4.98 MiB/s   
[0:02:49] Receiving objects:  83% (411076/493734), 362.19 MiB | 4.94 MiB/s   
[0:02:50] Receiving objects:  83% (411907/493734), 367.39 MiB | 5.00 MiB/s   
[0:02:52] Receiving objects:  83% (413395/493734), 377.57 MiB | 5.06 MiB/s   
[0:02:54] Receiving objects:  83% (414648/493734), 387.22 MiB | 5.00 MiB/s   
[0:02:55] Receiving objects:  84% (415434/493734), 392.12 MiB | 4.93 MiB/s   
[0:02:57] Receiving objects:  84% (419449/493734), 400.03 MiB | 4.98 MiB/s   
[0:02:58] Receiving objects:  85% (419908/493734), 415.29 MiB | 6.80 MiB/s   
[0:02:59] Receiving objects:  85% (419908/493734), 431.96 MiB | 9.39 MiB/s   
[0:03:00] Receiving objects:  85% (419908/493734), 447.69 MiB | 11.83 MiB/s   
[0:03:01] Receiving objects:  85% (419909/493734), 463.48 MiB | 14.09 MiB/s   
[0:03:02] Receiving objects:  85% (419910/493734), 479.69 MiB | 16.11 MiB/s   
[0:03:03] Receiving objects:  85% (419910/493734), 493.35 MiB | 15.53 MiB/s   
[0:03:04] Receiving objects:  85% (419910/493734), 504.71 MiB | 14.43 MiB/s   
[0:03:06] Receiving objects:  85% (419910/493734), 536.30 MiB | 14.35 MiB/s   
[0:03:07] Receiving objects:  85% (419910/493734), 552.46 MiB | 14.39 MiB/s   
[0:03:08] Receiving objects:  85% (419910/493734), 568.09 MiB | 14.87 MiB/s   
[0:03:09] Receiving objects:  85% (419910/493734), 583.85 MiB | 15.75 MiB/s   
[0:03:11] Receiving objects:  85% (419910/493734), 615.92 MiB | 15.89 MiB/s   
[0:03:12] Receiving objects:  85% (419910/493734), 632.33 MiB | 16.04 MiB/s   
[0:03:13] Receiving objects:  85% (419910/493734), 648.16 MiB | 16.02 MiB/s   
[0:03:14] Receiving objects:  85% (419910/493734), 664.59 MiB | 16.11 MiB/s   
[0:03:15] Receiving objects:  85% (419910/493734), 680.32 MiB | 16.11 MiB/s   
[0:03:16] Receiving objects:  85% (419910/493734), 696.93 MiB | 16.15 MiB/s   
[0:03:17] Receiving objects:  85% (419910/493734), 713.09 MiB | 16.15 MiB/s   
[0:03:19] Receiving objects:  85% (419910/493734), 729.53 MiB | 16.18 MiB/s   
[0:03:20] Receiving objects:  85% (419910/493734), 745.70 MiB | 16.28 MiB/s   
[0:03:21] Receiving objects:  85% (419910/493734), 761.56 MiB | 16.11 MiB/s   
[0:03:22] Receiving objects:  85% (419910/493734), 763.95 MiB | 12.76 MiB/s   
[0:03:23] Receiving objects:  85% (419910/493734), 779.65 MiB | 12.69 MiB/s   
[0:03:24] Receiving objects:  85% (419910/493734), 796.32 MiB | 12.75 MiB/s   
[0:03:25] Receiving objects:  85% (419910/493734), 812.48 MiB | 12.74 MiB/s   
[0:03:26] Receiving objects:  85% (419910/493734), 825.14 MiB | 12.13 MiB/s   
[0:04:56] Receiving objects:  85% (419910/493734), 828.99 MiB | 8.71 MiB/s   
[0:05:04] Receiving objects:  85% (419910/493734), 829.24 MiB | 9.00 KiB/s   
[0:05:06] Receiving objects:  85% (419910/493734), 833.36 MiB | 219.00 KiB/s   
[0:05:08] error: index-pack died of signal 9
[0:05:08] fatal: index-pack failed
[0:05:10] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src/tools /home/ubuntu/webrtc-build/src/_gclient_tools_cho9slqy' in '/home/ubuntu/webrtc-build' attempt 2 / 2

[0:05:10] Cloning into '/home/ubuntu/webrtc-build/src/_gclient_tools_cho9slqy'...
[0:05:11] remote: Sending approximately 1.16 GiB ...
[0:05:11] remote: Counting objects: 1   
[0:05:11] remote: Counting objects: 971, done
[0:05:11] remote: Finding sources:   1% (10/971)   
[0:05:11] remote: Finding sources:  10% (98/971)   
[0:05:11] remote: Finding sources: 100% (971/971)   
[0:05:11] Receiving objects:   0% (1/493734)   
[0:05:12] Receiving objects:   1% (4938/493734), 5.07 MiB | 5.07 MiB/s   
[0:05:14] Receiving objects:   4% (19750/493734), 13.95 MiB | 5.58 MiB/s   
[0:05:15] Receiving objects:   7% (34562/493734), 20.25 MiB | 5.78 MiB/s   
[0:05:16] Receiving objects:   9% (45599/493734), 26.08 MiB | 5.79 MiB/s   
[0:05:16] Receiving objects:  10% (49374/493734), 29.07 MiB | 5.91 MiB/s   
[0:05:17] Receiving objects:  13% (64186/493734), 35.02 MiB | 5.99 MiB/s   
[0:05:18] Receiving objects:  16% (78998/493734), 40.63 MiB | 5.92 MiB/s   
[0:05:19] Receiving objects:  37% (182682/493734), 48.10 MiB | 6.18 MiB/s   
[0:05:20] Receiving objects:  62% (306116/493734), 57.05 MiB | 6.87 MiB/s   
[0:05:22] Receiving objects:  72% (359719/493734), 72.45 MiB | 7.65 MiB/s   
[0:05:24] Receiving objects:  74% (365364/493734), 79.94 MiB | 7.04 MiB/s   
[0:05:25] Receiving objects:  74% (368904/493734), 87.85 MiB | 5.53 MiB/s   
[0:05:26] Receiving objects:  74% (369575/493734), 92.95 MiB | 5.08 MiB/s   
[0:05:28] Receiving objects:  75% (370301/493734), 101.13 MiB | 5.14 MiB/s   
[0:05:29] Receiving objects:  75% (370853/493734), 109.45 MiB | 5.38 MiB/s   
[0:05:31] Receiving objects:  75% (371730/493734), 120.10 MiB | 5.42 MiB/s   
[0:05:33] Receiving objects:  75% (373179/493734), 128.48 MiB | 5.45 MiB/s   
[0:05:34] Receiving objects:  75% (374759/493734), 136.93 MiB | 5.47 MiB/s   
[0:05:36] Receiving objects:  76% (377652/493734), 145.07 MiB | 5.54 MiB/s   
[0:05:37] Receiving objects:  76% (379123/493734), 150.43 MiB | 5.52 MiB/s   
[0:05:38] Receiving objects:  77% (380782/493734), 158.27 MiB | 5.37 MiB/s   
[0:05:39] Receiving objects:  77% (382109/493734), 163.67 MiB | 5.34 MiB/s   
[0:05:40] Receiving objects:  77% (383170/493734), 168.84 MiB | 5.28 MiB/s   
[0:05:42] Receiving objects:  77% (384884/493734), 179.34 MiB | 5.24 MiB/s   
[0:05:43] Receiving objects:  78% (385437/493734), 184.26 MiB | 5.16 MiB/s   
[0:05:45] Receiving objects:  78% (387540/493734), 191.91 MiB | 5.11 MiB/s   
[0:05:46] Receiving objects:  78% (388153/493734), 197.11 MiB | 5.10 MiB/s   
[0:05:47] Receiving objects:  79% (390050/493734), 204.66 MiB | 5.07 MiB/s   
[0:05:49] Receiving objects:  79% (391441/493734), 214.52 MiB | 5.01 MiB/s   
[0:05:50] Receiving objects:  79% (391947/493734), 219.77 MiB | 5.02 MiB/s   
[0:05:51] Receiving objects:  79% (392943/493734), 224.52 MiB | 4.93 MiB/s   
[0:05:53] Receiving objects:  80% (394988/493734), 231.86 MiB | 4.92 MiB/s   
[0:05:54] Receiving objects:  80% (396210/493734), 239.32 MiB | 4.90 MiB/s   
[0:05:56] Receiving objects:  80% (398296/493734), 246.80 MiB | 4.95 MiB/s   
[0:05:57] Receiving objects:  80% (399600/493734), 251.92 MiB | 5.01 MiB/s   
[0:05:59] Receiving objects:  81% (402123/493734), 262.49 MiB | 5.14 MiB/s   
[0:06:00] Receiving objects:  81% (403423/493734), 270.30 MiB | 5.21 MiB/s   
[0:06:02] Receiving objects:  81% (404207/493734), 280.48 MiB | 5.14 MiB/s   
[0:06:03] Receiving objects:  82% (405116/493734), 285.34 MiB | 5.06 MiB/s   
[0:06:05] Receiving objects:  82% (406448/493734), 294.99 MiB | 4.91 MiB/s   
[0:06:07] Receiving objects:  82% (408260/493734), 302.23 MiB | 4.83 MiB/s   
[0:06:08] Receiving objects:  82% (408869/493734), 309.46 MiB | 4.79 MiB/s   
[0:06:10] Receiving objects:  82% (409024/493734), 316.06 MiB | 4.68 MiB/s   
[0:06:12] Receiving objects:  82% (409542/493734), 325.49 MiB | 4.63 MiB/s   
[0:06:14] Receiving objects:  82% (409725/493734), 334.97 MiB | 4.58 MiB/s   
[0:06:15] Receiving objects:  83% (409800/493734), 342.05 MiB | 4.75 MiB/s   
[0:06:17] Receiving objects:  83% (409963/493734), 349.30 MiB | 4.77 MiB/s   
[0:06:18] Receiving objects:  83% (410350/493734), 353.98 MiB | 4.71 MiB/s   
[0:06:20] Receiving objects:  83% (411693/493734), 363.83 MiB | 4.82 MiB/s   
[0:06:22] Receiving objects:  83% (413114/493734), 374.02 MiB | 4.95 MiB/s   
[0:06:23] Receiving objects:  83% (413836/493734), 378.95 MiB | 5.02 MiB/s   
[0:06:24] Receiving objects:  84% (414737/493734), 386.42 MiB | 5.01 MiB/s   
[0:06:26] Receiving objects:  84% (417222/493734), 393.72 MiB | 4.91 MiB/s   
[0:06:27] Receiving objects:  84% (419335/493734), 399.28 MiB | 5.04 MiB/s   
[0:06:28] Receiving objects:  85% (419908/493734), 411.79 MiB | 6.21 MiB/s   
[0:06:29] Receiving objects:  85% (419908/493734), 427.67 MiB | 8.62 MiB/s   
[0:06:30] Receiving objects:  85% (419908/493734), 443.73 MiB | 11.09 MiB/s   
[0:06:31] Receiving objects:  85% (419909/493734), 459.95 MiB | 13.48 MiB/s   
[0:06:32] Receiving objects:  85% (419910/493734), 476.42 MiB | 16.03 MiB/s   
[0:06:33] Receiving objects:  85% (419910/493734), 492.83 MiB | 16.28 MiB/s   
[0:06:34] Receiving objects:  85% (419910/493734), 509.46 MiB | 16.32 MiB/s   
[0:06:35] Receiving objects:  85% (419910/493734), 525.79 MiB | 16.44 MiB/s   
[0:06:36] Receiving objects:  85% (419910/493734), 542.20 MiB | 16.42 MiB/s   
[0:06:37] Receiving objects:  85% (419910/493734), 558.26 MiB | 16.35 MiB/s   
[0:06:38] Receiving objects:  85% (419910/493734), 574.39 MiB | 16.28 MiB/s   
[0:06:39] Receiving objects:  85% (419910/493734), 591.20 MiB | 16.30 MiB/s   
[0:06:40] Receiving objects:  85% (419910/493734), 607.37 MiB | 16.26 MiB/s   
[0:06:41] Receiving objects:  85% (419910/493734), 623.84 MiB | 16.34 MiB/s   
[0:06:42] Receiving objects:  85% (419910/493734), 640.33 MiB | 16.39 MiB/s   
[0:06:43] Receiving objects:  85% (419910/493734), 656.97 MiB | 16.42 MiB/s   
[0:06:44] Receiving objects:  85% (419910/493734), 672.82 MiB | 16.30 MiB/s   
[0:06:45] Receiving objects:  85% (419910/493734), 689.00 MiB | 16.28 MiB/s   
[0:06:46] Receiving objects:  85% (419910/493734), 705.39 MiB | 16.29 MiB/s   
[0:06:48] Receiving objects:  85% (419910/493734), 737.95 MiB | 16.22 MiB/s   
[0:06:49] Receiving objects:  85% (419910/493734), 754.50 MiB | 16.33 MiB/s   
[0:06:50] Receiving objects:  85% (419910/493734), 770.54 MiB | 16.26 MiB/s   
[0:06:52] Receiving objects:  85% (419910/493734), 786.46 MiB | 16.21 MiB/s   
[0:06:53] error: index-pack died of signal 9
[0:06:53] fatal: index-pack failed
Traceback (most recent call last):
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 1177, in _Clone
    self._Run(clone_cmd,
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 1518, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_utils.py", line 715, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src/tools /home/ubuntu/webrtc-build/src/_gclient_tools_cho9slqy' returned non-zero exit status 128 in /home/ubuntu/webrtc-build
[0:06:57] _____ Conflicting directory found in /home/ubuntu/webrtc-build/src/tools. Moving to /home/ubuntu/webrtc-build/_bad_scm/src/toolsagxymik1.
----------------------------------------


Warnings:
Conflicting directory /home/ubuntu/webrtc-build/src/tools moved to /home/ubuntu/webrtc-build/_bad_scm/src/toolsagxymik1.
Traceback (most recent call last):
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 647, in update
    self._Clone(revision, url, options)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 1177, in _Clone
    self._Run(clone_cmd,
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 1518, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_utils.py", line 715, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src/tools /home/ubuntu/webrtc-build/src/_gclient_tools_cho9slqy' returned non-zero exit status 128 in /home/ubuntu/webrtc-build

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.vpython-root/c43f4d/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/webrtc-build/src/tools' -> '/home/ubuntu/webrtc-build/_bad_scm/src/toolsagxymik1/tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/webrtc-build/depot_tools/metrics.py", line 291, in print_notice_and_exit
    yield
  File "/home/ubuntu/webrtc-build/depot_tools/gclient.py", line 3489, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ubuntu/webrtc-build/depot_tools/gclient.py", line 3475, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/ubuntu/webrtc-build/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/ubuntu/webrtc-build/depot_tools/gclient.py", line 3026, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient.py", line 2020, in RunOnDeps
    work_queue.flush(revision_overrides,
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_utils.py", line 1013, in flush
    reraise(e[0], e[1], e[2])
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_utils.py", line 70, in reraise
    raise value
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_utils.py", line 1090, in run
    self.item.run(*self.args, **self.kwargs)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient.py", line 1005, in run
    self._got_revision = self._used_scm.RunCommand(command, options, args,
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 128, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 650, in update
    self._DeleteOrMove(options.force)
  File "/home/ubuntu/webrtc-build/depot_tools/gclient_scm.py", line 203, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "/home/ubuntu/.vpython-root/c43f4d/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/home/ubuntu/.vpython-root/c43f4d/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ubuntu/.vpython-root/c43f4d/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/webrtc-build/src/tools'

Subprocess failed with return code 1.
```

Thanks

**Comment by SantosLV** [comment]
Yeap, it was indeed a configuration issue.

Thanks for pointing out.
